# Generated by Django 4.1.2 on 2022-10-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_expense_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
