# Generated by Django 4.1.2 on 2022-10-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_totals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Totals',
        ),
    ]
